### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by wasurocks** [WaelYasmina/pixitutorial#1]
Hi Wael, I've followed your instructions on the `README.md` and tried opening `index.html` using two browsers. Unfortunately, the error pops up as per the following images I've pasted.

Firefox Dev Edition:
<img width="1150" alt="Screen Shot 2565-02-22 at 12 18 25" src="https://user-images.githubusercontent.com/38748581/155067764-ea6b4d48-c913-4b78-a674-075c63af896f.png">

Chrome:
<img width="1726" alt="Screen Shot 2565-02-22 at 12 18 41" src="https://user-images.githubusercontent.com/38748581/155067794-b0c4efce-48ae-45d0-a842-c245a8502780.png">

**Comment by WaelYasmina** [comment]
Hi!
It turns out you're not running a server.
Install the "Live Server" extension on VSCode, open the HTML code, right click and hit "Open with Live Server".

**Comment by wasurocks** [comment]
Ahh I see, I thought it would be running without a server like a normal script. Do you happen to know why that can't be done with pixi? Thanks ahead

**Comment by WaelYasmina** [comment]
It's not Pixi but browsers are not allowing it for security reasons. Google "CORS" for detailed explanations.
No problem!

**Comment by WaelYasmina** [comment]
It's not Pixi but browsers that are not allowing it for security reasons. Google "CORS" for detailed explanations.
No problem!

**Comment by wasurocks** [comment]
Thank you!
